name: Download and Update File

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间0点运行
  workflow_dispatch:      # 允许手动触发

jobs:
  download-and-update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # 使用最新版本v4
      with:
        token: ${{ secrets.GH_TOKEN }}  # 使用PAT
        fetch-depth: 0  # 获取完整历史记录

    - name: Download file
      run: |
        curl -sSfLo speed.yaml "https://bestsub.bestrui.ggff.net/share/bestsub/cdcefaa4-1f0d-462e-ba76-627b344989f2/speed.yaml"  # -s静默 -S显示错误 -f失败时不保存 -L跟随重定向 -o指定输出文件
       
    - name: Commit and push changes
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}  # 再次声明以便git push使用
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add all.yaml
        
        # 只有文件有变化时才提交
        if git diff --quiet --cached; then
          echo "No changes detected"
        else
          git commit -m "Update downloaded file [$(date +'%Y-%m-%d %H:%M:%S')]"
          git push origin HEAD:${{ github.ref }}
        fi


